#! /bin/bash

if [ $# -lt 1 ] ; then
  echo "Usage: compile <source file>"
  exit 1
fi

source=$1

out=$(basename $source)
out=${out%.*}

loki-clang -ccc-host-triple loki-elf-linux -O3 -L/home/db434/Public/lokilib $source -llokilib -o $out
